apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-app
  labels:
    app: my-fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-fastapi-app
  template:
    metadata:
      labels:
        app: my-fastapi-app
    spec:
      imagePullSecrets:
      - name: $(imagePullSecret)    
      containers:
      - name: my-fastapi-app
        image: $(containerRegistry)/$(imageRepository):$(tag)
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "sqlite:///./test.db"  # Update this with your actual database URL if needed
